"""Rules a migration must satisfy before it can merge.

Alembic will autogenerate a migration from a model diff, and the generated file is very
often nearly right — which is the problem. Nearly right passes review, and the three ways
it is wrong are all invisible in a diff:

**A dropped column looks like a rename.** Autogenerate sees `old_name` gone and `new_name`
present and writes a drop plus an add. On an empty database that is identical to a rename.
On a populated one it silently deletes the data.

**A non-nullable column with no default cannot be added to a populated table.** It works
in CI against an empty schema and fails in production, at the worst moment, halfway
through a deploy.

**Schema and data changes in one migration cannot be rolled back independently.** The
schema part reverses cleanly; the data part usually cannot, so the whole migration becomes
one-way the moment they are combined.

These are checked mechanically rather than by asking a reviewer to remember them.

Task ids: M31.2.2.2, M31.2.2.3, M31.2.2.4, M31.2.2.5
"""

from __future__ import annotations

import ast
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
VERSIONS = REPO / "migrations" / "versions"

#: Left by alembic revision --autogenerate and meant to be replaced by a human.
AUTOGENERATE_MARKERS = (
    "### commands auto generated by Alembic",
    "### end Alembic commands ###",
)

DROP_COLUMN = re.compile(r"op\.drop_column\(", re.IGNORECASE)
ADD_COLUMN = re.compile(r"op\.add_column\(", re.IGNORECASE)
NOT_NULL = re.compile(r"nullable\s*=\s*False", re.IGNORECASE)
HAS_DEFAULT = re.compile(r"server_default\s*=", re.IGNORECASE)
DML = re.compile(r"\b(INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM)\b", re.IGNORECASE)
NOT_IMPLEMENTED = re.compile(r"raise\s+NotImplementedError")


@dataclass(frozen=True)
class Finding:
    file: str
    rule: str
    detail: str

    def __str__(self) -> str:
        return f"{self.file}: {self.rule} — {self.detail}"


def _downgrade_state(text: str) -> str:
    """Whether the file has a downgrade, and whether it does anything: parsed, not counted.

    Three answers: `"missing"`, `"empty"` and `"present"`.

    **This was a line count and the line count had a hole.** The old rule flagged a body
    whose last line was `pass` only when the whole body was two lines or fewer, so a
    downgrade gutted to `pass` passed clean the moment it carried a docstring or a commented
    out statement, which is exactly what a gutted downgrade looks like: somebody deleted the
    statements and left the explanation. Found by an agent's mutation of an unrelated
    migration and reproduced before this was changed.

    An `ast` parse asks the real question rather than a proxy for it. A docstring and
    comments are not statements, so no amount of prose makes an empty body look full.

    A file that will not parse is reported as missing rather than passed over. A migration
    with a syntax error has no downgrade in any sense that matters, and returning "present"
    for it would make the one file nobody can run the file nobody checks.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return "missing"

    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or node.name != "downgrade":
            continue
        body = list(node.body)
        # A leading string expression is the docstring, and a docstring is not a statement.
        if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant):
            if isinstance(body[0].value.value, str):
                body = body[1:]
        if not body or all(isinstance(stmt, ast.Pass) for stmt in body):
            return "empty"
        return "present"
    return "missing"


def check_file(path: Path) -> list[Finding]:
    text = path.read_text(encoding="utf-8")
    name = path.name
    findings: list[Finding] = []

    for marker in AUTOGENERATE_MARKERS:
        if marker in text:
            findings.append(
                Finding(
                    name,
                    "unreviewed autogeneration",
                    "still carries Alembic's generated markers; a human has not read it",
                )
            )
            break

    down = _downgrade_state(text)
    if down == "missing":
        findings.append(Finding(name, "no downgrade", "a deploy with no way back"))
    elif down == "empty":
        # An empty downgrade is either a mistake or a deliberate one-way change. The
        # deliberate case says so with NotImplementedError and a reason; `pass` says
        # nothing and is indistinguishable from forgetting. `raise NotImplementedError` is
        # a statement, so a deliberate one-way migration passes this on its own.
        findings.append(
            Finding(
                name,
                "empty downgrade",
                "use `raise NotImplementedError` with the reason if it is genuinely one-way",
            )
        )

    if DROP_COLUMN.search(text) and ADD_COLUMN.search(text):
        findings.append(
            Finding(
                name,
                "possible rename written as drop plus add",
                "identical on an empty database, silently destructive on a populated one; "
                "use alter_column or say in a comment why the data may be lost",
            )
        )

    for line in text.splitlines():
        if ADD_COLUMN.search(line) and NOT_NULL.search(line) and not HAS_DEFAULT.search(line):
            findings.append(
                Finding(
                    name,
                    "not-null column with no server_default",
                    "works against an empty CI schema, fails against a populated table "
                    "halfway through a production deploy",
                )
            )
            break

    has_schema = bool(
        ADD_COLUMN.search(text) or DROP_COLUMN.search(text) or "op.create_table" in text
    )
    if has_schema and DML.search(text):
        findings.append(
            Finding(
                name,
                "schema and data change in one migration",
                "the schema half reverses and the data half usually cannot, so combining "
                "them makes the whole thing one-way",
            )
        )

    return findings


def check_all(versions: Path = VERSIONS) -> list[Finding]:
    findings: list[Finding] = []
    for path in sorted(versions.glob("*.py")):
        findings.extend(check_file(path))
    return findings


def main() -> int:
    findings = check_all()
    if not findings:
        count = len(list(VERSIONS.glob("*.py")))
        print(f"ok: {count} migration(s) satisfy the policy")
        return 0
    print("migration policy violations:", file=sys.stderr)
    for f in findings:
        print(f"  {f}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
