"""Rules a migration must satisfy before it can merge.

Alembic will autogenerate a migration from a model diff, and the generated file is very
often nearly right — which is the problem. Nearly right passes review, and the three ways
it is wrong are all invisible in a diff:

**A dropped column looks like a rename.** Autogenerate sees `old_name` gone and `new_name`
present and writes a drop plus an add. On an empty database that is identical to a rename.
On a populated one it silently deletes the data.

**A non-nullable column with no default cannot be added to a populated table.** It works
in CI against an empty schema and fails in production, at the worst moment, halfway
through a deploy.

**Schema and data changes in one migration cannot be rolled back independently.** The
schema part reverses cleanly; the data part usually cannot, so the whole migration becomes
one-way the moment they are combined.

These are checked mechanically rather than by asking a reviewer to remember them.

**And one rule that is not about autogeneration at all.** `brain_fastlane` is the role the
fast lane reads under, and M6.1.3 is the property that it reaches projected tables and
nothing else. That property is a fact about every migration ever written rather than about
any one of them: 0001 created the role, 0008 handed it `SELECT` on `proj.record`, and the
way it would be lost is a migration written next year adding `GRANT SELECT ON know.chunk TO
brain_fastlane` because a fast answer needed a document. The check lives here because this
is the one function every migration is already put through, so the rule applies to files
nobody has written yet. See `THE_FAST_LANE_REACHES_PROJECTED_TABLES_AND_NOTHING_ELSE`.

Task ids: M6.1.3, M31.2.2.2, M31.2.2.3, M31.2.2.4, M31.2.2.5
"""

from __future__ import annotations

import ast
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
VERSIONS = REPO / "migrations" / "versions"

#: Left by alembic revision --autogenerate and meant to be replaced by a human.
AUTOGENERATE_MARKERS = (
    "### commands auto generated by Alembic",
    "### end Alembic commands ###",
)

DROP_COLUMN = re.compile(r"op\.drop_column\(", re.IGNORECASE)
ADD_COLUMN = re.compile(r"op\.add_column\(", re.IGNORECASE)
NOT_NULL = re.compile(r"nullable\s*=\s*False", re.IGNORECASE)
HAS_DEFAULT = re.compile(r"server_default\s*=", re.IGNORECASE)
DML = re.compile(r"\b(INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM)\b", re.IGNORECASE)
NOT_IMPLEMENTED = re.compile(r"raise\s+NotImplementedError")

#: The role the fast lane reads under, and the schema it may read in.
FAST_LANE_ROLE = "brain_fastlane"
PROJECTED_SCHEMA = "proj"

#: Why a migration may not widen what the fast lane reaches (M6.1.3).
THE_FAST_LANE_REACHES_PROJECTED_TABLES_AND_NOTHING_ELSE = (
    "The fast lane answers with no model in the loop, so nothing downstream reads what it "
    "returns and nothing can notice it returned the wrong thing. What keeps that safe is "
    "how little it can reach: one role, NOBYPASSRLS, holding USAGE on proj and SELECT on "
    "the projected tables. Every later migration is an opportunity to widen that by one "
    "table, each time for a good reason, and the widening is invisible in a diff about "
    "something else. So a grant or a policy naming this role is checked against a closed "
    "list of shapes, and anything not on it is a finding rather than a judgement call."
)

#: A privilege statement mentioning the role. Bounded at the statement separator so one
#: statement in a multi-statement literal cannot absorb the next.
_FAST_LANE_GRANT = re.compile(r"\bGRANT\b[^;]*?\bbrain_fastlane\b[^;]*", re.IGNORECASE)
_FAST_LANE_POLICY = re.compile(r"\bCREATE\s+POLICY\b[^;]*?\bbrain_fastlane\b[^;]*", re.IGNORECASE)

#: The only shapes allowed. Deny by default: a statement matching none of these is a
#: finding, which is the right direction for a check that is not a SQL parser and must not
#: become one. What it costs is a legitimate new shape needing a line added here, in a
#: module whose docstring says why, which is the review this rule exists to force.
_FAST_LANE_ALLOWED: tuple[re.Pattern[str], ...] = (
    # The role handed to somebody else. This widens whoever receives it, not the fast lane,
    # and `GRANT brain_fastlane TO brain_app` in 0001 is how the application can assume it.
    re.compile(r"GRANT\s+brain_fastlane\s+TO\s+[\w?]+$", re.IGNORECASE),
    # Reaching into the projected schema at all.
    re.compile(r"GRANT\s+USAGE\s+ON\s+SCHEMA\s+proj\s+TO\s+brain_fastlane$", re.IGNORECASE),
    # Reading one projected table. SELECT alone: no INSERT, no UPDATE, no DELETE, no ALL.
    re.compile(r"GRANT\s+SELECT\s+ON\s+proj\.\w+\s+TO\s+brain_fastlane$", re.IGNORECASE),
    # And the policy without which the grant returns an empty table under row-level
    # security, which is indistinguishable from an empty database.
    re.compile(
        r"CREATE\s+POLICY\s+\w+\s+ON\s+proj\.\w+\s+FOR\s+SELECT\s+TO\s+brain_fastlane\b.*",
        re.IGNORECASE,
    ),
)


@dataclass(frozen=True)
class Finding:
    file: str
    rule: str
    detail: str

    def __str__(self) -> str:
        return f"{self.file}: {self.rule} — {self.detail}"


def _function_body(text: str, name: str) -> str:
    """The source of one top-level function, or an empty string.

    Parsed rather than sliced on indentation, so a nested definition or a string containing
    `def upgrade()` does not confuse it. Returns empty for a file that will not parse, which
    the downgrade check reports separately and more usefully.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return ""
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            return ast.get_source_segment(text, node) or ""
    return ""


def _is_docstring(stmt: ast.stmt) -> bool:
    """Whether this statement is a docstring rather than something the migration does."""
    return (
        isinstance(stmt, ast.Expr)
        and isinstance(stmt.value, ast.Constant)
        and isinstance(stmt.value.value, str)
    )


def _downgrade_state(text: str) -> str:
    """Whether the file has a downgrade, and whether it does anything: parsed, not counted.

    Three answers: `"missing"`, `"empty"` and `"present"`.

    **This was a line count and the line count had a hole.** The old rule flagged a body
    whose last line was `pass` only when the whole body was two lines or fewer, so a
    downgrade gutted to `pass` passed clean the moment it carried a docstring or a commented
    out statement, which is exactly what a gutted downgrade looks like: somebody deleted the
    statements and left the explanation. Found by an agent's mutation of an unrelated
    migration and reproduced before this was changed.

    An `ast` parse asks the real question rather than a proxy for it. A docstring and
    comments are not statements, so no amount of prose makes an empty body look full.

    A file that will not parse is reported as missing rather than passed over. A migration
    with a syntax error has no downgrade in any sense that matters, and returning "present"
    for it would make the one file nobody can run the file nobody checks.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return "missing"

    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or node.name != "downgrade":
            continue
        body = list(node.body)
        # A leading string expression is the docstring, and a docstring is not a statement.
        if body and _is_docstring(body[0]):
            body = body[1:]
        if not body or all(isinstance(stmt, ast.Pass) for stmt in body):
            return "empty"
        return "present"
    return "missing"


def _sql_literals(text: str) -> list[str]:
    """Every string a migration could execute, with whitespace collapsed.

    Read from the parse tree rather than from the file's text, and that is the whole reason
    this helper exists. Half the migrations in this repository argue about `brain_fastlane`
    in their docstrings, and 0008's says the words "granted SELECT" in a sentence explaining
    why it is the only grant there is. A text search would report the explanation as the
    violation, which is the failure mode that gets a check switched off.

    Docstrings and bare string expressions are dropped: neither can be executed. An f-string
    is rendered with `?` where each substituted value goes, because the values in these
    files are role-name constants and the shape of the statement is what is being checked.
    Its literal fragments are dropped separately, or `f"GRANT x TO {ROLE}"` would also be
    read as the truncated statement `GRANT x TO`.

    Sound and incomplete, and the incompleteness is worth naming: a statement assembled from
    a variable at run time is invisible here. Every migration in this repository writes its
    statements as literals, and a future one that does not would need a reviewer rather than
    this function.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []

    skip: set[int] = set()
    for node in ast.walk(tree):
        for child in ast.iter_child_nodes(node):
            if isinstance(child, ast.Expr) and isinstance(child.value, ast.Constant):
                skip.add(id(child.value))
        if isinstance(node, ast.JoinedStr):
            skip.update(id(part) for part in node.values)

    out: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.JoinedStr):
            rendered = "".join(
                part.value
                if isinstance(part, ast.Constant) and isinstance(part.value, str)
                else "?"
                for part in node.values
            )
            out.append(" ".join(rendered.split()))
        elif (
            isinstance(node, ast.Constant) and isinstance(node.value, str) and id(node) not in skip
        ):
            out.append(" ".join(node.value.split()))
    return out


def _fast_lane_findings(name: str, text: str) -> list[Finding]:
    """Grants and policies naming the fast-lane role, checked against a closed list (M6.1.3).

    Both directions are read from the same literals: a grant *to* the role widens what it
    reaches, and a grant *of* the role widens who can assume it. Only the first is what
    M6.1.3 is about, and `GRANT brain_app TO brain_fastlane` is the shape that looks like the
    second and is the first, which is why the allowed list matches whole statements rather
    than looking for the role on one side of the word TO.
    """
    findings: list[Finding] = []
    for literal in _sql_literals(text):
        if FAST_LANE_ROLE not in literal.lower():
            continue
        for pattern in (_FAST_LANE_GRANT, _FAST_LANE_POLICY):
            for statement in pattern.findall(literal):
                if any(allowed.search(statement) for allowed in _FAST_LANE_ALLOWED):
                    continue
                findings.append(
                    Finding(
                        name,
                        "fast lane reaches past the projected tables",
                        f"{statement.strip()!r} is not one of the shapes the fast-lane role "
                        f"may be given. {THE_FAST_LANE_REACHES_PROJECTED_TABLES_AND_NOTHING_ELSE}",
                    )
                )
    return findings


def check_file(path: Path) -> list[Finding]:
    text = path.read_text(encoding="utf-8")
    name = path.name
    findings: list[Finding] = []

    for marker in AUTOGENERATE_MARKERS:
        if marker in text:
            findings.append(
                Finding(
                    name,
                    "unreviewed autogeneration",
                    "still carries Alembic's generated markers; a human has not read it",
                )
            )
            break

    down = _downgrade_state(text)
    if down == "missing":
        findings.append(Finding(name, "no downgrade", "a deploy with no way back"))
    elif down == "empty":
        # An empty downgrade is either a mistake or a deliberate one-way change. The
        # deliberate case says so with NotImplementedError and a reason; `pass` says
        # nothing and is indistinguishable from forgetting. `raise NotImplementedError` is
        # a statement, so a deliberate one-way migration passes this on its own.
        findings.append(
            Finding(
                name,
                "empty downgrade",
                "use `raise NotImplementedError` with the reason if it is genuinely one-way",
            )
        )

    # Within `upgrade` alone, not across the file. A column addition puts `add_column` in
    # `upgrade` and `drop_column` in `downgrade`, which is the correct shape and not a
    # rename, and reading the whole file flagged every such migration: the first one written
    # after this rule existed tripped it, which is how the false positive was found.
    #
    # The message also used to offer an escape the rule did not implement, saying a comment
    # would satisfy it when nothing looked for one. A rule whose message describes a way out
    # that does not exist is worse than a strict rule, because the person who follows the
    # instruction and still fails concludes the check is broken and reaches for the
    # suppression.
    upgrade_body = _function_body(text, "upgrade")
    if DROP_COLUMN.search(upgrade_body) and ADD_COLUMN.search(upgrade_body):
        findings.append(
            Finding(
                name,
                "possible rename written as drop plus add",
                "identical on an empty database, silently destructive on a populated one; "
                "use alter_column, which preserves the data",
            )
        )

    for line in text.splitlines():
        if ADD_COLUMN.search(line) and NOT_NULL.search(line) and not HAS_DEFAULT.search(line):
            findings.append(
                Finding(
                    name,
                    "not-null column with no server_default",
                    "works against an empty CI schema, fails against a populated table "
                    "halfway through a production deploy",
                )
            )
            break

    has_schema = bool(
        ADD_COLUMN.search(text) or DROP_COLUMN.search(text) or "op.create_table" in text
    )
    if has_schema and DML.search(text):
        findings.append(
            Finding(
                name,
                "schema and data change in one migration",
                "the schema half reverses and the data half usually cannot, so combining "
                "them makes the whole thing one-way",
            )
        )

    findings.extend(_fast_lane_findings(name, text))

    return findings


def check_all(versions: Path = VERSIONS) -> list[Finding]:
    findings: list[Finding] = []
    for path in sorted(versions.glob("*.py")):
        findings.extend(check_file(path))
    return findings


def main() -> int:
    findings = check_all()
    if not findings:
        count = len(list(VERSIONS.glob("*.py")))
        print(f"ok: {count} migration(s) satisfy the policy")
        return 0
    print("migration policy violations:", file=sys.stderr)
    for f in findings:
        print(f"  {f}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
