"""The rules a migration must satisfy before it can merge.

Task ids: M31.2.2.2, M31.2.2.3, M31.2.2.4, M31.2.2.5
"""

from __future__ import annotations

from pathlib import Path

from brain.ops.migration_policy import Finding, check_all, check_file

NL = "\n"


def migration(up: list[str], down: list[str] | None = None) -> str:
    """Build a migration body from lines, so no test carries an unwieldy string literal."""
    body = "def upgrade() -> None:" + NL
    body += "".join(f"    {line}{NL}" for line in up)
    if down is not None:
        body += NL + "def downgrade() -> None:" + NL
        body += "".join(f"    {line}{NL}" for line in down)
    return body


def write(tmp_path: Path, body: str) -> Path:
    p = tmp_path / "0002_thing.py"
    p.write_text(body, encoding="utf-8")
    return p


def rules(findings: list[Finding]) -> set[str]:
    return {f.rule for f in findings}


# ----------------------------------------------------------- the real ones
def test_the_migrations_in_this_repository_pass() -> None:
    """The policy has to hold for what is already here, or it is aspirational."""
    assert check_all() == []


# ------------------------------------------------------------- autogenerate
def test_alembics_own_markers_mean_nobody_read_it(tmp_path: Path) -> None:
    """Autogenerate is very often nearly right, and nearly right passes review."""
    p = write(
        tmp_path,
        migration(
            ["### commands auto generated by Alembic ###", "pass"],
            ["op.drop_table('x')"],
        ),
    )
    assert "unreviewed autogeneration" in rules(check_file(p))


# ---------------------------------------------------------------- reversal
def test_a_missing_downgrade_is_a_deploy_with_no_way_back(tmp_path: Path) -> None:
    p = write(tmp_path, migration(["op.create_table('x')"]))
    assert "no downgrade" in rules(check_file(p))


def test_an_empty_downgrade_is_indistinguishable_from_forgetting(tmp_path: Path) -> None:
    """A genuinely one-way migration says so with NotImplementedError and a reason.
    `pass` says nothing, and cannot be told apart from having forgotten."""
    p = write(tmp_path, migration(["op.create_table('x')"], ["pass"]))
    assert "empty downgrade" in rules(check_file(p))


def test_a_deliberate_one_way_migration_is_accepted(tmp_path: Path) -> None:
    p = write(
        tmp_path,
        migration(
            ["op.create_table('x')"],
            ['raise NotImplementedError("the source rows are gone; restore from backup")'],
        ),
    )
    assert "empty downgrade" not in rules(check_file(p))
    assert "no downgrade" not in rules(check_file(p))


# ------------------------------------------------------------------ renames
def test_a_drop_plus_an_add_is_flagged_as_a_possible_rename(tmp_path: Path) -> None:
    """Autogenerate cannot tell a rename from a delete-and-create. On an empty database
    the two are identical; on a populated one the second silently destroys the data."""
    p = write(
        tmp_path,
        migration(
            ["op.drop_column('t', 'old')", "op.add_column('t', sa.Column('new', sa.String()))"],
            ["op.drop_column('t', 'new')"],
        ),
    )
    assert "possible rename written as drop plus add" in rules(check_file(p))


# ------------------------------------------------------------- not-null adds
def test_a_not_null_column_without_a_default_is_flagged(tmp_path: Path) -> None:
    """Works against an empty CI schema, fails against a populated table halfway through
    a production deploy - the worst possible moment to find out."""
    p = write(
        tmp_path,
        migration(
            ["op.add_column('t', sa.Column('c', sa.String(), nullable=False))"],
            ["op.drop_column('t', 'c')"],
        ),
    )
    assert "not-null column with no server_default" in rules(check_file(p))


def test_a_not_null_column_with_a_default_is_fine(tmp_path: Path) -> None:
    add = "op.add_column('t', sa.Column('c', sa.String(), nullable=False, server_default='x'))"
    p = write(tmp_path, migration([add], ["op.drop_column('t', 'c')"]))
    assert "not-null column with no server_default" not in rules(check_file(p))


# --------------------------------------------------------- schema plus data
def test_schema_and_data_in_one_migration_is_flagged(tmp_path: Path) -> None:
    """The schema half reverses cleanly and the data half usually cannot, so combining
    them makes the whole migration one-way."""
    p = write(
        tmp_path,
        migration(
            [
                "op.add_column('t', sa.Column('c', sa.String()))",
                "op.execute(\"UPDATE t SET c = 'x'\")",
            ],
            ["op.drop_column('t', 'c')"],
        ),
    )
    assert "schema and data change in one migration" in rules(check_file(p))


def test_a_pure_data_migration_is_not_flagged(tmp_path: Path) -> None:
    """Data-only is allowed; it is the mixture that cannot be reversed by halves."""
    p = write(
        tmp_path,
        migration(
            ["op.execute(\"UPDATE t SET c = 'x'\")"],
            ['op.execute("UPDATE t SET c = NULL")'],
        ),
    )
    assert "schema and data change in one migration" not in rules(check_file(p))
