#!/bin/sh
# Import the Company Brain realm into a Keycloak server, and check what landed.
#
# This exists because the alternative is a realm configured by clicking, whose current
# state nobody can diff and whose restore procedure is somebody's memory. The realm next
# to this file is the reviewed version; this script is the only supported way to put it
# somewhere, so "what is configured" and "what is in the repository" cannot drift silently.
#
# THIS SCRIPT HAS NEVER BEEN RUN. There is no Keycloak in this repository's compose file
# and none was contacted while writing it. It is a reviewed procedure, not a tested one:
# the flags below are from the kcadm documentation for Keycloak 26, and the first real run
# should be against a throwaway server, not a client's.
#
# Usage:
#   KEYCLOAK_URL=https://id.example.com \
#   KEYCLOAK_ADMIN=admin \
#   KEYCLOAK_ADMIN_PASSWORD=... \
#   ops/keycloak/setup.sh
#
# The password comes from the environment and never from an argument. Arguments are visible
# in `ps` to every user on the box, and a credential that leaks that way leaks to somebody
# who was not looking for it.
#
# Task ids: M1.1.1

set -eu

URL="${KEYCLOAK_URL:-}"
ADMIN_USER="${KEYCLOAK_ADMIN:-admin}"
REALM="${KEYCLOAK_REALM:-brain}"
ADMIN_REALM="${KEYCLOAK_ADMIN_REALM:-master}"
DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
SOURCE="$DIR/realm-export.json"

# kcadm ships inside the Keycloak distribution. Named rather than searched for, because a
# `which kcadm.sh` that finds a different version's client is worse than not finding one.
KCADM="${KCADM:-kcadm.sh}"

fail() {
  echo "setup.sh: $1" >&2
  exit 1
}

[ -n "$URL" ] || fail "KEYCLOAK_URL is not set"
[ -n "${KEYCLOAK_ADMIN_PASSWORD:-}" ] || fail "KEYCLOAK_ADMIN_PASSWORD is not set"
[ -f "$SOURCE" ] || fail "cannot find $SOURCE"
command -v "$KCADM" >/dev/null 2>&1 || fail "$KCADM is not on PATH; it ships with Keycloak"

# jq is required rather than optional. The realm file carries `_comment` keys explaining
# every decision in it, and Keycloak's importer rejects properties it does not recognise,
# so the comments have to come out on the way in.
#
# Rejected: dropping the comments from the file so no filter is needed. The settings that
# matter here are the ones whose consequence is invisible (directAccessGrantsEnabled,
# webOrigins, revokeRefreshToken), and a reviewer reading an uncommented realm export has
# no way to tell a deliberate choice from a default.
command -v jq >/dev/null 2>&1 || fail "jq is required to strip the _comment keys before import"

case "$URL" in
  https://*) ;;
  http://localhost*|http://127.0.0.1*)
    # Allowed only here. An admin password over plaintext to anything else is the password
    # gone, and "it is just staging" is where every one of these starts.
    echo "==> WARNING: plaintext admin session to $URL (local only)" >&2
    ;;
  *) fail "refusing to send an admin password to $URL over plaintext" ;;
esac

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT INT TERM
jq 'walk(if type == "object" then del(._comment) else . end)' "$SOURCE" > "$TMP"

echo "==> logging in to $URL as $ADMIN_USER (realm $ADMIN_REALM)"
"$KCADM" config credentials \
  --server "$URL" \
  --realm "$ADMIN_REALM" \
  --user "$ADMIN_USER" \
  --password "$KEYCLOAK_ADMIN_PASSWORD"

if "$KCADM" get "realms/$REALM" >/dev/null 2>&1; then
  echo "==> realm $REALM exists; updating it in place"
  # Update rather than delete-and-recreate. Deleting a realm deletes its users, their
  # federated identity links and every session, so a re-import to change one flag would sign
  # the whole company out and orphan every principal_identity row pointing at a subject.
  "$KCADM" update "realms/$REALM" -f "$TMP"
else
  echo "==> creating realm $REALM"
  "$KCADM" create realms -f "$TMP"
fi

echo "==> verifying what landed"
# Read the settings back rather than trusting the import's exit code. Keycloak's importer
# ignores fields it does not understand for the version it is running, so a realm can import
# cleanly and still be missing the thing the import was for. These four are the ones whose
# absence is a security change rather than a cosmetic one.
for field in sslRequired defaultSignatureAlgorithm revokeRefreshToken ssoSessionMaxLifespan; do
  value=$("$KCADM" get "realms/$REALM" --fields "$field" | jq -r ".$field // \"MISSING\"")
  echo "    $field = $value"
  [ "$value" != "MISSING" ] || fail "$field did not survive the import"
done

for client in brain-console brain-api brain-sync; do
  found=$("$KCADM" get clients -r "$REALM" --query "clientId=$client" | jq -r 'length')
  [ "$found" = "1" ] || fail "client $client is not present after import (found $found)"
  echo "    client $client ok"
done

# The service account's secret is generated by Keycloak and printed once. It is echoed here
# rather than written to a file: a secret in a file on a deploy host is a secret in a backup.
# It belongs in OpenBao, pasted from this output.
echo "==> brain-sync client secret (store in OpenBao, then clear your scrollback)"
SYNC_ID=$("$KCADM" get clients -r "$REALM" --query "clientId=brain-sync" | jq -r '.[0].id')
"$KCADM" get "clients/$SYNC_ID/client-secret" -r "$REALM" | jq -r '.value'

cat <<EOF

==> configure the application with:
    issuer   $URL/realms/$REALM
    jwks     $URL/realms/$REALM/protocol/openid-connect/certs
    audience brain-api

The issuer string must match byte for byte. brain.identity.oidc compares it exactly, on
purpose: normalising a trailing slash is how a hostile issuer whose hostname merely starts
the same way gets accepted by a comparison somebody wrote to be forgiving.

Still to do by hand, because neither belongs in a file that gets copied between
environments:
  * set redirectUris and webOrigins on brain-console to the real hostname; the file ships
    .invalid placeholders so a stale realm import cannot become an open redirect
  * add the client's SAML identity provider from the disabled template, and check it
    against brain.identity.oidc.SamlFederation before enabling it
EOF
